CREATE TABLE repositories (
                              id BIGSERIAL PRIMARY KEY,
                              github_id BIGINT NOT NULL UNIQUE,
                              owner TEXT NOT NULL,
                              name TEXT NOT NULL,
                              full_name TEXT NOT NULL UNIQUE,
                              description TEXT,
                              stars BIGINT NOT NULL DEFAULT 0,
                              forks BIGINT NOT NULL DEFAULT 0,
                              open_issues BIGINT NOT NULL DEFAULT 0,
                              subscribers BIGINT NOT NULL DEFAULT 0,
                              language TEXT,
                              license TEXT,
                              archived BOOLEAN NOT NULL DEFAULT FALSE,
                              has_issues BOOLEAN NOT NULL DEFAULT TRUE,
                              url TEXT NOT NULL,
                              default_branch TEXT NOT NULL,
                              topics TEXT[] NOT NULL DEFAULT '{}',
                              github_created_at TEXT NOT NULL,
                              github_updated_at TEXT NOT NULL,
                              pushed_at TEXT NOT NULL,
                              readme TEXT NOT NULL DEFAULT '',
                              created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                              updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);